import './styles.css'
import type { Metadata } from 'next'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout(props: { children: React.ReactNode }) {
    return (
        <html lang="en" className="bg-gray-50">
            <body>{props.children}</body>
        </html>
    )
}
